name: dog_adoption_app
description: Aplicativo para cadastro e listagem de cães para adoção.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.2.2
  sqlite3: ^2.7.5
  sembast: ^3.8.4+1
  sembast_web: ^2.4.1
  sembast_sqflite: ^2.2.1
  path_provider: ^2.1.5
  provider: ^6.1.5

flutter:
  assets:
    - assets/images/adote.png
    - assets/icons/